export const SET_STUDENTHOSTINGARRAY = 'SET_STUDENTHOSTINGARRAY'

export const SET_STUDENTDETAILS = 'SET_STUDENTDETAILS'

export const SET_CLASSINFO = 'SET_CLASSINFO'

export const SET_CURRENTTRUSTEESHIP = 'SET_CURRENTTRUSTEESHIP'

export const SET_CURRENTIMAGEARRAY = 'SET_CURRENTIMAGEARRAY'

export const SET_FEEDBACKID = 'SET_FEEDBACKID'
