
export const SET_CLASSID = 'SET_CLASSID'

export const SET_SAVECLASS = 'SET_SAVECLASS'

export const CLEAR_SAVECLASS = 'CLEAR_SAVECLASS'

export const SET_CLASSDETAILS = 'SET_CLASSDETAILS'

export const SET_CSTUDENTID = 'SET_CSTUDENTID'

export const SET_WEEKNAMELIST = 'SET_WEEKNAMELIST'

export const SET_CACHETEACHERID = 'SET_CACHETEACHERID'
