
export const SET_USERID = 'SET_USERID'

export const SET_TEACHERDETAILS = 'SET_TEACHERDETAILS'

export const SET_BASEINFO = 'SET_BASEINFO'

export const SET_CLASSINFO = 'SET_CLASSINFO'

export const SET_TEACHERNIFO = 'SET_TEACHERNIFO'

export const SET_CLASSLISTS = 'SET_CLASSLISTS'

export const SET_TITLE = 'SET_TITLE'

export const SET_SCORE = 'SET_SCORE'

export const CLEAR_ADDTEACHER = 'CLEAR_ADDTEACHER'

export const SET_ADDTEACHER = 'SET_ADDTEACHER'

export const SET_ISADD = 'SET_ISADD'

export const SET_PROFILE = 'SET_PROFILE'

export const SET_TEACHERCLASSNAME = 'SET_TEACHERCLASSNAME'

export const SET_HOUSEHOLDADDRESSARR = 'SET_HOUSEHOLDADDRESSARR'

export const SET_HOUSEHOLDADDRESSNAME = 'SET_HOUSEHOLDADDRESSNAME'

export const SET_DEGREEARR = 'SET_DEGREEARR'

export const SET_DEGREENAME = 'SET_DEGREENAME'

export const SET_ISCACHE = 'SET_ISCACHE'
